-- ============================================================
-- Seed original content for About, Services, Craftsmanship, FAQ
-- Run this in Supabase SQL Editor
-- ============================================================

-- ABOUT
DELETE FROM about_content;
INSERT INTO about_content (title, body) VALUES (
  'About Khalaj Amani Carpets',
  E'Weaving heritage, one knot at a time, from the heart of Kabul.\n\n## Our Roots in Kabul\n\nKhalaj Amani Carpets is a handmade carpet production company based in the historic Chaman Huzori area of Kabul, Afghanistan. Located at ACMEG 1st, Second Floor, Room #24 on Jada e Maiwand, our workshop sits in a district long associated with craft, trade, and the enduring spirit of Afghan artistry.\n\nWe specialize exclusively in authentic hand-knotted and handwoven carpets produced by skilled Afghan weavers. Every piece that leaves our workshop is the result of traditional techniques, natural materials, and the patient dedication of artisans whose knowledge has been passed down through families for generations.\n\nOur name — Khalaj Amani — reflects both heritage and aspiration: the Khalaj cultural lineage and the word "Amani," which carries meanings of peace, safety, and lasting value. We aim to create carpets that bring beauty and lasting quality into homes around the world.\n\n## What We Stand For\n\n**Master Craftsmanship**\nOur weavers are experienced artisans who work exclusively by hand. We maintain high standards of knot density, design fidelity, and finishing so that every carpet is worthy of the tradition it represents.\n\n**Natural Materials**\nWe prioritize hand-spun Afghan wool, natural vegetable dyes (madder, indigo, and others), and carefully selected foundations. Where silk is used, it is chosen for quality and luminosity.\n\n**Authenticity First**\nWe do not produce machine-made imitations. Every carpet is genuinely handmade in Afghanistan. We are transparent about materials, origin, and the time required to create each piece.\n\n**From Kabul to the World**\nWhile our roots are firmly in Kabul, we serve clients internationally — private collectors, interior designers, hotels, and families seeking lasting, meaningful floor art.\n\n## Our Workshop & Process\n\nProduction takes place in our Kabul workshop under the supervision of experienced masters. Designs range from classical medallion and tribal geometric patterns to more contemporary interpretations and fully bespoke commissions. Clients can request specific sizes, colorways, and motifs. Lead times vary according to size and complexity — typically several months for fine hand-knotted pieces.\n\nWe also offer restoration and careful cleaning guidance for existing Afghan and related carpets, helping preserve pieces that already carry history.\n\nWhether you are furnishing a home, specifying for a project, or seeking a single heirloom piece, Khalaj Amani Carpets exists to provide authentic, high-quality handmade carpets with clear provenance and honest craftsmanship.'
);

-- SERVICES
DELETE FROM services_content;
INSERT INTO services_content (title, body) VALUES (
  'Our Services',
  E'Beyond ready pieces — we support custom work, restoration, shipping and professional consultation.\n\n## Bespoke / Custom Commissions\nCommission a unique carpet made to your exact size, color palette and design. Our master weavers can interpret traditional Afghan motifs, create contemporary geometric compositions, or work from your own inspiration. Typical lead times range from 4 to 12 months depending on dimensions and complexity. Ideal for architects, interior designers and private clients seeking a true one-of-a-kind heirloom.\n\n## Restoration & Repair\nWe carefully restore and repair existing Afghan and related handmade carpets. Services include re-knotting damaged areas, fringe and edge repair, foundation strengthening, and professional cleaning guidance. Each restoration is assessed individually so that the original character of the piece is preserved as far as possible.\n\n## Worldwide Shipping\nWe arrange secure, insured shipping to destinations around the world. Carpets are carefully rolled, wrapped and packed to protect the pile and structure during transit. Shipping costs and transit times are quoted on a case-by-case basis according to size, destination and preferred service level.\n\n## Interior & Project Consultation\nWe work with interior designers, architects and project teams to select or commission carpets that suit specific spaces — residential, hospitality or commercial. We can provide recommendations on size, scale, color and collection type to complement your overall design vision.\n\n## Wholesale & Trade\nTrade clients and retailers are welcome to enquire about wholesale arrangements. We can discuss volume, lead times, exclusive designs and ongoing supply. Please contact us with details of your business and requirements.\n\n## Care Guidance & After-Sales\nEvery carpet is accompanied by clear care instructions tailored to its materials (wool, silk blend, kilim, etc.). We remain available after purchase to advise on cleaning, rotation, storage and minor maintenance so that your carpet ages gracefully for decades.'
);

-- CRAFTSMANSHIP
DELETE FROM craftsmanship_content;
INSERT INTO craftsmanship_content (title, body) VALUES (
  'Craftsmanship',
  E'The patient, human process behind every authentic handmade Afghan carpet.\n\nAt Khalaj Amani Carpets we remain committed to traditional hand methods. No machine weaving is used. The result is a living object with texture, slight irregularities and character that only human hands can create.\n\n## 01 — Design & Planning\nEach carpet begins with a design. Classical medallion, tribal geometric, floral garden or contemporary compositions are drawn and sized according to the intended final dimensions. For bespoke work we refine the design in dialogue with the client before weaving begins.\n\n## 02 — Material Selection\nWe select hand-spun Afghan wool for its resilience, natural lanolin and ability to take dye beautifully. Where silk accents are required, high-quality silk is chosen for its luminous sheen. Foundations are typically cotton or wool, prepared to the density required by the design.\n\n## 03 — Natural Dyeing\nTraditional vegetable dyes — madder for reds, indigo for blues, and other natural sources — are used wherever possible. The dyeing process is carefully controlled so that colors are rich, light-fast and harmonious. Natural abrash (subtle tonal variation) is often embraced as a mark of handwork.\n\n## 04 — Hand Knotting\nThe carpet is woven on a vertical loom. Each knot is tied by hand by experienced weavers. Knot density (KPSI) varies by collection — from robust tribal weaves to ultra-fine pieces exceeding 200 knots per square inch. A single large carpet can take many months of continuous work.\n\n## 05 — Washing & Finishing\nAfter the weaving is complete the carpet is washed, stretched and finished. Edges are secured, fringes are prepared, and the pile is sheared to an even height. Some pieces receive a special wash to create a softer, antique-style appearance while remaining fully new and durable.\n\n## 06 — Quality Inspection\nEvery carpet is inspected for design fidelity, structural integrity, color consistency and overall finish before it is offered for sale or shipped. Only pieces that meet our standards leave the workshop under the Khalaj Amani name.'
);

-- FAQ (12 original questions)
DELETE FROM faqs;
INSERT INTO faqs (question, answer, sort_order, is_published) VALUES
('Are your carpets truly handmade in Afghanistan?', 'Yes. Every carpet offered by Khalaj Amani Carpets is produced by hand in our workshop and associated weaving facilities in Kabul, Afghanistan. We do not sell machine-made carpets.', 1, true),
('What materials do you use?', 'Primarily hand-spun Afghan wool and natural vegetable dyes. Some pieces include silk accents or pure silk. Foundations are typically cotton or wool. Exact materials are listed for each product.', 2, true),
('How are prices determined?', 'Prices depend on size, knot density (KPSI), materials (wool vs silk), design complexity and current market conditions. All prices are provided on enquiry so we can give accurate, up-to-date quotations.', 3, true),
('Do you ship internationally?', 'Yes. We arrange secure, insured international shipping. Cost and transit time depend on the size of the carpet and the destination. We will quote shipping as part of any order discussion.', 4, true),
('Can I commission a custom size or design?', 'Absolutely. Bespoke commissions are one of our core services. You can specify dimensions, colors and design direction. Lead times typically range from 4 to 12 months depending on the piece.', 5, true),
('How should I care for my carpet?', 'Professional cleaning is recommended for most hand-knotted pieces. Regular vacuuming (without a beater bar) and prompt attention to spills help. Detailed care instructions are supplied with each carpet according to its materials.', 6, true),
('What is KPSI and why does it matter?', 'KPSI means knots per square inch. Higher KPSI generally indicates a finer, more detailed and often more time-consuming weave. Our range includes robust tribal weaves as well as ultra-fine pieces over 200 KPSI.', 7, true),
('Do you offer restoration services?', 'Yes. We assess and restore existing handmade carpets — re-knotting, edge and fringe repair, structural strengthening and cleaning guidance. Contact us with photos and details of the piece.', 8, true),
('How long does a typical carpet take to make?', 'It varies widely. A small prayer rug may take weeks; a large, fine medallion carpet can take many months of continuous weaving by skilled hands.', 9, true),
('Can I visit the workshop in Kabul?', 'Visits can be arranged by prior appointment when conditions allow. Please contact us in advance so we can coordinate a suitable time.', 10, true),
('What payment methods do you accept?', 'We discuss payment terms on a case-by-case basis for international orders. Common methods include bank transfer. Details are confirmed once an order is agreed.', 11, true),
('Are the colors light-fast?', 'Natural dyes used properly have good light-fastness, though prolonged direct sunlight will gradually affect any textile. We recommend rotating carpets periodically and using UV-protective window treatments where possible.', 12, true);
